// Mocks generated by Mockito 5.4.6 from annotations
// in typing_speed_master/test/mocks/typed_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:math' as _i2;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:typing_speed_master/features/typing_test/provider/typing_test_provider.dart'
    as _i4;
import 'package:typing_speed_master/models/typing_test_result_model.dart'
    as _i5;
import 'package:typing_speed_master/theme/provider/theme_provider.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRandom_0 extends _i1.SmartFake implements _i2.Random {
  _FakeRandom_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMaterialColor_2 extends _i1.SmartFake implements _i3.MaterialColor {
  _FakeMaterialColor_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TypingProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTypingProvider extends _i1.Mock implements _i4.TypingProvider {
  MockTypingProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Random get random =>
      (super.noSuchMethod(
            Invocation.getter(#random),
            returnValue: _FakeRandom_0(this, Invocation.getter(#random)),
          )
          as _i2.Random);

  @override
  List<int> get typingSpeedSamples =>
      (super.noSuchMethod(
            Invocation.getter(#typingSpeedSamples),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  List<DateTime> get typingTimestamps =>
      (super.noSuchMethod(
            Invocation.getter(#typingTimestamps),
            returnValue: <DateTime>[],
          )
          as List<DateTime>);

  @override
  List<_i5.TypingTestResultModel> get results =>
      (super.noSuchMethod(
            Invocation.getter(#results),
            returnValue: <_i5.TypingTestResultModel>[],
          )
          as List<_i5.TypingTestResultModel>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  String get selectedDifficulty =>
      (super.noSuchMethod(
            Invocation.getter(#selectedDifficulty),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#selectedDifficulty),
            ),
          )
          as String);

  @override
  Duration get selectedDuration =>
      (super.noSuchMethod(
            Invocation.getter(#selectedDuration),
            returnValue: _FakeDuration_1(
              this,
              Invocation.getter(#selectedDuration),
            ),
          )
          as Duration);

  @override
  String get currentOriginalText =>
      (super.noSuchMethod(
            Invocation.getter(#currentOriginalText),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#currentOriginalText),
            ),
          )
          as String);

  @override
  String get currentUserInput =>
      (super.noSuchMethod(
            Invocation.getter(#currentUserInput),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#currentUserInput),
            ),
          )
          as String);

  @override
  double get averageWPM =>
      (super.noSuchMethod(Invocation.getter(#averageWPM), returnValue: 0.0)
          as double);

  @override
  double get averageAccuracy =>
      (super.noSuchMethod(Invocation.getter(#averageAccuracy), returnValue: 0.0)
          as double);

  @override
  double get averageConsistency =>
      (super.noSuchMethod(
            Invocation.getter(#averageConsistency),
            returnValue: 0.0,
          )
          as double);

  @override
  int get totalTests =>
      (super.noSuchMethod(Invocation.getter(#totalTests), returnValue: 0)
          as int);

  @override
  set random(_i2.Random? value) => super.noSuchMethod(
    Invocation.setter(#random, value),
    returnValueForMissingStub: null,
  );

  @override
  set typingSpeedSamples(List<int>? value) => super.noSuchMethod(
    Invocation.setter(#typingSpeedSamples, value),
    returnValueForMissingStub: null,
  );

  @override
  set typingTimestamps(List<DateTime>? value) => super.noSuchMethod(
    Invocation.setter(#typingTimestamps, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setDifficulty(String? difficulty) => super.noSuchMethod(
    Invocation.method(#setDifficulty, [difficulty]),
    returnValueForMissingStub: null,
  );

  @override
  void setDuration(Duration? duration) => super.noSuchMethod(
    Invocation.method(#setDuration, [duration]),
    returnValueForMissingStub: null,
  );

  @override
  String getCurrentText() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentText, []),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getCurrentText, []),
            ),
          )
          as String);

  @override
  void moveToNextText() => super.noSuchMethod(
    Invocation.method(#moveToNextText, []),
    returnValueForMissingStub: null,
  );

  @override
  void getRandomText() => super.noSuchMethod(
    Invocation.method(#getRandomText, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateUserInput(String? userInput) => super.noSuchMethod(
    Invocation.method(#updateUserInput, [userInput]),
    returnValueForMissingStub: null,
  );

  @override
  void recordTypingSpeedSample(int? charCount, DateTime? timestamp) =>
      super.noSuchMethod(
        Invocation.method(#recordTypingSpeedSample, [charCount, timestamp]),
        returnValueForMissingStub: null,
      );

  @override
  double calculateConsistency() =>
      (super.noSuchMethod(
            Invocation.method(#calculateConsistency, []),
            returnValue: 0.0,
          )
          as double);

  @override
  void resetConsistencyTracking() => super.noSuchMethod(
    Invocation.method(#resetConsistencyTracking, []),
    returnValueForMissingStub: null,
  );

  @override
  List<int> calculateIncorrectCharPositions(
    String? userInput,
    String? originalText,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateIncorrectCharPositions, [
              userInput,
              originalText,
            ]),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i7.Future<void> saveResultWithErrorTracking(
    String? userInput,
    String? originalText,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveResultWithErrorTracking, [
              userInput,
              originalText,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveResult(_i5.TypingTestResultModel? result) =>
      (super.noSuchMethod(
            Invocation.method(#saveResult, [result]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteHistoryEntry(_i5.TypingTestResultModel? result) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHistoryEntry, [result]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> verifySupabaseConnection() =>
      (super.noSuchMethod(
            Invocation.method(#verifySupabaseConnection, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void clearHistory() => super.noSuchMethod(
    Invocation.method(#clearHistory, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i5.TypingTestResultModel> getRecentResults(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentResults, [count]),
            returnValue: <_i5.TypingTestResultModel>[],
          )
          as List<_i5.TypingTestResultModel>);

  @override
  List<_i5.TypingTestResultModel> getAllRecentResults() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRecentResults, []),
            returnValue: <_i5.TypingTestResultModel>[],
          )
          as List<_i5.TypingTestResultModel>);

  @override
  _i5.TypingTestResultModel? getResultByTimestamp(DateTime? timestamp) =>
      (super.noSuchMethod(Invocation.method(#getResultByTimestamp, [timestamp]))
          as _i5.TypingTestResultModel?);

  @override
  String getOriginalTextForResult(_i5.TypingTestResultModel? result) =>
      (super.noSuchMethod(
            Invocation.method(#getOriginalTextForResult, [result]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getOriginalTextForResult, [result]),
            ),
          )
          as String);

  @override
  String getUserInputForResult(_i5.TypingTestResultModel? result) =>
      (super.noSuchMethod(
            Invocation.method(#getUserInputForResult, [result]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getUserInputForResult, [result]),
            ),
          )
          as String);

  @override
  void resetCurrentTest() => super.noSuchMethod(
    Invocation.method(#resetCurrentTest, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeProvider extends _i1.Mock implements _i9.ThemeProvider {
  MockThemeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isDarkMode =>
      (super.noSuchMethod(Invocation.getter(#isDarkMode), returnValue: false)
          as bool);

  @override
  _i3.ThemeMode get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i3.ThemeMode.system,
          )
          as _i3.ThemeMode);

  @override
  _i3.MaterialColor get primaryColor =>
      (super.noSuchMethod(
            Invocation.getter(#primaryColor),
            returnValue: _FakeMaterialColor_2(
              this,
              Invocation.getter(#primaryColor),
            ),
          )
          as _i3.MaterialColor);

  @override
  String get currentColorName =>
      (super.noSuchMethod(
            Invocation.getter(#currentColorName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#currentColorName),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> toggleTheme() =>
      (super.noSuchMethod(
            Invocation.method(#toggleTheme, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setTheme(bool? isDark) =>
      (super.noSuchMethod(
            Invocation.method(#setTheme, [isDark]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setPrimaryColor(String? colorName) =>
      (super.noSuchMethod(
            Invocation.method(#setPrimaryColor, [colorName]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
